### ISSUE TITLE
Identify areas for work on shakesearch

### ISSUE THREAD

**Issue by zeptonaut** [zeptonaut/shakesearch#1]
In this issue, I'll do my best to communicate my strategy for improving the shakesearch app in a reasonable timeframe.

To begin, let's restate the prompt from the README:

> In it's current state, however, the app is in rough shape. The search is case sensitive, the results are difficult to read, and the search is limited to exact matches.
> 
> ...
> 
> Improve the app! Think about the problem from the user's perspective and prioritize your changes according to what you think is most useful.
> 
> You can approach this with a back-end, front-end, or full-stack focus.

# What are people trying to accomplish with the site?
It's important to anchor any discussion with "what needs to be improved" with answers to "who's this built for?" and "what are they trying to accomplish?". In real life, I'd probably either:

 1. be the target user myself, in which case I have intuition for those answers and hope others share the same problem or
 2. go find people who have the problem and talk to them. (After all, if I can't find them now, how would I expect to find them after this is built?)

Given that this is an interview question, we're going to have to use our imagination here a bit.

I'm going to say that there are two general use cases here: 

1. I want an easy way to find a particular passage from Shakespeare that I'm thinking of and then share it with others ("What did Romeo say to Juliet again when he was waiting at her window?")
2. I want an easy way to query for groups of passages that might share something in common (e.g. "How many times did Romeo say the word "boy" in _Romeo and Juliet_?")

Any improvement should be made with those two primary use cases in mind.

**Comment by zeptonaut** [comment]
Now that we've identified what problems we're solving, let's move on to "how could the site do a better job at solving those problems?"

I'll divide these into three sections: general, finding a passage, and sharing it with others:

# General
- **General lack of readability**: The results are extremely hard to parse. Which book does each result belong to? Which character said it? Where does one quote end and another begin? Where does the actual searched string appear within each quote?
- **Speed**: The search can be pretty slow. Interestingly, I don't actually think the _search_ is that slow: typing "Romeo" into the bar and hitting search returns results in a near-instantaneous result. However, typing "I" into the bar and hitting search takes ~15 seconds before results are shown. To me, this says that the scanning isn't what's slow but either returning large result sets to the frontend or adding those results to the site for display within the frontend. 
- **Lack of loading indicator**: It's often hard to visually tell when a query is executing. You can't tell when a query stops executing if it returns zero results.
- **Case sensitivity**: As mentioned in the prompt, I think case sensitivity is a problem. Sometimes case sensitivity is important, but that's the exception rather than the norm. Given an option, I'd take the option of case sensitivity: given only a default, I'd choose no case sensitivity.

# Finding a passage
- **Unable to filter results meaningfully.**: When I'm trying to find something in particular, I do so by narrowing: "What was that quote? I think it was in Hamlet and I think it included the word "Tree". ([For an amazing example of narrowing, see the McMaster-Carr website.](https://www.mcmaster.com/)).

# Sharing it with others
- **Results aren't linkable.** If you're trying to settle an argument with the site (let's be honest, the most realistic use case), then you can't even provide a source for your argument-winning fact. Furthermore, working linking is extremely important because it encourages people to share the site, thereby increasing its reach.
- **Basic result stats**: I certainly imagine for "grouped" results it'd be useful to have some very basic aggregate statistics about the result set. How many results were there?

# Nonissues
- **Fuzzy matching**: Despite the prompt above, I don't see a lack of fuzzy matching as particularly harmful to either of these target use cases. A lack of substring matching certainly would be, but the current application works with substring matching.

**Comment by zeptonaut** [comment]
# Prioritizing the issues
Next, I think it makes sense to prioritize these issues, vaguely by "how important are they to the usage of the site and how much time will each take?"

- [x] **Decent looking output** (#2): No matter the features that are added, the results are basically impossible to parse right now. Adding some basic styling would go a long way. 
- [x] **Feedback that a search is in progress** (#3): Adding some sort of feedback that a search is in progress would also go a long way towards improving usability.
- [x] **Fixing whatever's making large result sets slow.** (#4): I suspect this probably has to do with just how many DOM nodes are getting added to the page, but I could also see it having to do with serialization of the response or something.
- [x] **Linkability** (#5): Executing a search should update the URL. Going to a specific URL should execute a specific search. (These patterns are deeply embedded from how search engines have long worked and not having things work this way would be super confusing to users.)
- [x] **Get it up and running on Render** (#6): This is required for submission, so might as well do it now rather than tack it on to the end. 
- [x] **Search crashes when result is extremely common** (#7)
